name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: 'curl'

    - name: Install Dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        composer install

    - name: Run Tests
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        docker-host: tcp://localhost:2375

    - name: Build and Push Docker Image
      run: |
        docker build -t jpvaldez/laravel-webkit .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u jpvaldez --password-stdin
        docker push jpvaldez/laravel-webkit
